"""empty message

Revision ID: fe629852503d
Revises: 91627225b945
Create Date: 2020-12-26 11:09:59.298629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe629852503d'
down_revision = '91627225b945'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Movie', sa.Column('image_link', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Movie', 'image_link')
    # ### end Alembic commands ###
